import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../../useContext";
import {Poppins} from "next/font/google"

const inter = Inter({ subsets: ["latin"] });
const Poppin = Poppins({weight:'100',subsets:["latin"]})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="body" className={Poppin.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
