import type { Metadata } from "next";
import { Inter,Libre_Franklin,Roboto_Serif } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../../useContext";
import {Poppins} from "next/font/google"

const inter = Inter({ subsets: ["latin"] });
const libre= Libre_Franklin({subsets:["latin"]})
const Poppin = Poppins({weight:'100',subsets:["latin"]})
const roboto = Roboto_Serif({subsets:["latin"]})
export const metadata: Metadata = {
  title: "Starrtix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="body" className={roboto.className} >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
